# .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/universal:2

# [Optional] Uncomment to install a specific version of Node.js
# RUN sudo apt-get update && sudo apt-get install -y nodejs npm

# [Optional] Install any other tools or dependencies needed for your app